### ISSUE TITLE
gpgconf: command not found

### ISSUE THREAD

**Issue by jayvdb** [yegor256/rultor#1177]
On https://github.com/coala/coala-bears/pull/1743 , we are seeing `gpgconf: command not found` appear twice when rultor is asked to merge the PR.

**Comment by 0crat** [comment]
@yegor256 please, pay attention to this issue

**Comment by jayvdb** [comment]
The relevant code is:

```diff
$ git grep --context 5 gpgconf
src/main/java/com/rultor/agents/req/Decrypt.java-    public Iterable<String> commands() throws IOException {
src/main/java/com/rultor/agents/req/Decrypt.java-        final Collection<XML> assets =
src/main/java/com/rultor/agents/req/Decrypt.java-            this.profile.read().nodes("/p/entry[@key='decrypt']/entry");
src/main/java/com/rultor/agents/req/Decrypt.java-        final Collection<String> commands = new LinkedList<String>();
src/main/java/com/rultor/agents/req/Decrypt.java-        if (!assets.isEmpty()) {
src/main/java/com/rultor/agents/req/Decrypt.java:            commands.add("gpgconf --reload gpg-agent");
src/main/java/com/rultor/agents/req/Decrypt.java-            commands.add(
src/main/java/com/rultor/agents/req/Decrypt.java-                Joiner.on(' ').join(
src/main/java/com/rultor/agents/req/Decrypt.java-                    "gpg --keyserver hkp://pool.sks-keyservers.net",
src/main/java/com/rultor/agents/req/Decrypt.java-                    this.proxy,
src/main/java/com/rultor/agents/req/Decrypt.java-                    "--verbose --recv-keys 9AF0FA4C"
```

**Comment by jayvdb** [comment]
`gpgconf` is in the latest docker image:
```bash
$ docker run -t yegor256/rultor /usr/bin/gpgconf --version
gpg:GPG for OpenPGP:/usr/bin/gpg2
gpg-agent:GPG Agent:/usr/bin/gpg-agent
scdaemon:Smartcard Daemon:/usr/lib/gnupg2/scdaemon
gpgsm:GPG for S/MIME:/usr/bin/gpgsm
dirmngr:Directory Manager:/usr/bin/dirmngr
```

**Comment by jayvdb** [comment]
fwiw, after a little digging for https://github.com/yegor256/rultor/issues/1179, I can confirm that `Decrypt.commands()` has good coverage, but that doesnt mean that the commands are actually executed on the host.

**Comment by yegor256** [comment]
@jayvdb this is definitely a bug on the server, which hosts Docker. Give me a few minutes...

**Comment by yegor256** [comment]
@jayvdb I can't understand what needs to be done in order to install `gpgconf` on Ubuntu 16.04. Googling now... Maybe you know?

**Comment by yegor256** [comment]
@jayvdb I belive it's fixed now, after I installed `gnupg2` on all servers. Please check.

**Comment by jayvdb** [comment]
OK, rultor is now merging for us.

But I feel that the problem is not really solved with 6afc944fe70.
It is a bit of a shock that rultor itself is not running inside a container of some sort.
And somehow a recent deployment of rultor didnt include running acceptance tests.

This hit has rather hard, as the breakage occurred during a release, and while a PyCon sprint was occurring.  Three days without response on this issue is a long time.

It seems quite unlikely that `mailx` and `gnupg2` are the only two dependencies, in which case there is another similar problem waiting to happen in the future when Ubuntu changes some part of its packaging defaults.

And a quick sniff away I found https://github.com/yegor256/rultor/issues/1180

Could you identify the plan/create the issues that are needed to be better prepared for the next similar situation?  e.g.

If we created a Dockerfile for rultor itself, using dind (Docker in Docker), would that be implemented?

Can some of the scripts be modified so that more of the functionality is executed inside the 'per-build container' instead of outside?

**Comment by Hrabovszki1023** [comment]
THX @yegor256! 

I am Using - image: "yegor256/java-maven" and had the same problem. (-> FROM rultor).
Now it works again. 

Zoltán

**Comment by yegor256** [comment]
@jayvdb you're asking very good questions. Can we please close this issue as fixed and create a new one (or a few), where those problems will be discussed and solved. We definitely need proper solutions for them, in order to avoid those situations in the future.

**Comment by 0crat** [comment]
Oops! Job `gh:yegor256/rultor#1177` was not in scope
