### ISSUE TITLE
"Line has trailing spaces" error duing rultor build

### ISSUE THREAD

**Issue by dpisarenko** [yegor256/rultor#757]
When Travis CI builds rultor, it gets Qulice errors:

```
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[154]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[162]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[194]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[204]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[208]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[280]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[288]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[290]: Line has trailing spaces. (RegexpSinglelineCheck)
[ERROR] /src/main/resources/com/rultor/spi/talk.xsd[365]: Line has trailing spaces. (RegexpSinglelineCheck)
[INFO] Read our quality policy: http://www.qulice.com/quality.html
```

Full log: https://travis-ci.org/yegor256/rultor/builds/48042349

There are two strange phenomena:

  1. I didn't touch `talk.xsd`.
  1. On my machine, `talk.xsd` has only 152 lines and the errors in Travis start with line 154.

Please tell me, how I can fix this error.

**Comment by yegor256** [comment]
@dpisarenko how can I reproduce this in master branch?

**Comment by dpisarenko** [comment]
I suppose by running `mvn clean install -Pqulice`.

-- 
Дмитрий Писаренко
Dmitri Pisarenko



23.01.2015, 15:49, "Yegor Bugayenko" <notifications@github.com>:

**Comment by yegor256** [comment]
@dpisarenko hm.. indeed, Travis build is broken. how did this happen? rultor merged this pull request https://github.com/yegor256/rultor/pull/750 without any qulice complaints

**Comment by yegor256** [comment]
hm... rultor is not checking qulice :(

**Comment by yegor256** [comment]
@dpisarenko I fixed rultor config, in  62b8a84, thanks for the bug

**Comment by dpisarenko** [comment]
@yegor256 Thanks. I merged your changes into PR https://github.com/yegor256/rultor/pull/753 and it is building now. If the problem is fixed there, I'll close this issue.

**Comment by dpisarenko** [comment]
@yegor256 The build still fails https://travis-ci.org/yegor256/rultor/builds/48049910 . I did `git pull rultor master`, then pushed the code with the merges to the branch of my PR.

**Comment by alex-palevsky** [comment]
@yegor256 it is yours, help us

**Comment by alex-palevsky** [comment]
@dpisarenko thanks for reporting! I topped your account for 15 mins, transaction 50619376

**Comment by yegor256** [comment]
@dpisarenko this issue seems to be fixed. please close the ticket

**Comment by alex-palevsky** [comment]
@yegor256 Many thanks! **30 mins** were added to your account in Transaction ID `000-7afc3037`. +30 added to your rating, current score is: [+5518](http://www.netbout.com/b/35008?open=rating)
