### ISSUE TITLE
Rultor accepts a command and reports about an error

### ISSUE THREAD

**Issue by dmzaytsev** [yegor256/rultor#976]
Rultor accepts `merge` command and reports about an error in the same time

it looks like a bug

https://github.com/jcabi/jcabi-w3c/pull/30#issuecomment-169990320
https://github.com/teamed/xockets-xjm/pull/265#issuecomment-170002607
https://github.com/yegor256/takes/pull/500#issuecomment-170004296

![image](https://cloud.githubusercontent.com/assets/9972909/12198245/01fc44fe-b630-11e5-96b9-70db436c2aeb.png)

**Comment by yegor256** [comment]
@dmzaytsev thanks, it's fixed in 2ea2fea

**Comment by dmzaytsev** [comment]
@yegor256 It seems the issue not fixed yet https://github.com/yegor256/takes/pull/503#issuecomment-170236470

**Comment by yegor256** [comment]
@dmzaytsev fixed in c5260a9

**Comment by yegor256** [comment]
@rultor release, tag is `1.59.10`

**Comment by dmzaytsev** [comment]
@yegor256 

https://github.com/yegor256/netbout/pull/907#issuecomment-170864310
![image](https://cloud.githubusercontent.com/assets/9972909/12261056/9b561176-b940-11e5-97ca-ab0cec488315.png)
